### ISSUE TITLE
PhantomJS process dies when running on Windows 7 enterprise

### ISSUE THREAD

**Issue by DMIScottNoring** [TheJaredWilcurt/UGUI-pa11y#31]
Similar to using pa11y itself, Koa11y phantom process dies when running a report.  I don't see any logs or detail of the error but I'm assuming its the same that occurs with pa11y:

Error: HeadlessError: Phantom Process died
    at ClientRequest.<anonymous> (/usr/lib/node_modules/pa11y/node_modules/node-
phantom-simple/node-phantom-simple.js:659:12)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by TheJaredWilcurt** [comment]
@DMIScottNoring 
Thanks for reporting this. We are gearing up to do a new release of Koa11y 3.0.0. We've changed a lot since the last release (hence the bump from 2.0 to 3.0).

Can you try this to see if the new version still has this issue:

1. Install [Node.js](http://nodejs.org)
2. Download the latest code from our [3.0 branch](https://github.com/open-indy/Koa11y/archive/3.0.zip)
3. Unzip it to it's own folder
4. In command prompt, navigate to the unzipped folder
5. Run `npm install` (will take a few minutes)
6. Run `npm start`
7. Test it out and report back.

**Comment by DMIScottNoring** [comment]
I have the latest version already (3.0) The error was reported against that. Sorry I should have specified that.

**Comment by TheJaredWilcurt** [comment]
@DMIScottNoring 

I routinely run it on Win 7 Pro, which is one step down from Enterprise. According to Wikipedia the only difference between the two is:

> Enterprise edition was sold through volume licensing. Additional features include support for Multilingual User Interface, BitLocker Drive Encryption, UNIX application support, a license allowing the operating of diskless nodes (diskless PCs) and activation via VLK.

I don't think any of those feature differences should directly affect Koa11y. I'm guessing there's some security setting or something that is causing the issue.

You mentioned that just running Pa11y on it's own doesn't work either. Since we are simply a UI built on top of Pa11y, this seems like an issue on their end.

We are considering making much bigger changes in Koa11y 4.0. Including exploring adding an alternative engine to generate reports using aXe. So users could switch between the aXe and Pa11y. The latest versions of Pa11y are also switching from Phantom over to Puppeteer. So after we release Koa11y 3, we'll be working solely on Koa11y 4 and exploring these new engine options.

I'll update this ticket in the future to inform you once some of these new options are in the `4.0` branch.

**Comment by DMIScottNoring** [comment]
Thank you. Yes it is a pi11y issue which many have reported online.

**Comment by DanielRuf** [comment]
PhantomJS is not further developed and we should switch to Chrome headless / puppeteer.
